version: "2.3"

services:
  core-localstack:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SERVICES=${LSTACK_SERVICES:-s3}"
      - "DEFAULT_REGION=${AWS_REGION:-us-east-1}"
      - "HOSTNAME=${LSTACK_HOSTNAME:-localhost}"
      #- "USE_SSL=true"
      #- "DATA_DIR=${LOCALSTACK_DATA_DIR:-/tmp/localstack/data}" # uncomment if you want to persist data between runs
    ports:
      - "4567-4582:4567-4582"
      - "8080:8080"